/**:
  ros__parameters:
    wheel_radius: 0.11
    wheel_width: 0.12
    wheel_base: 1.3       # the real car size: 0.86 # between front wheel center and rear wheel center
    wheel_tread: 0.81     # the real car size: 0.66 # between left wheel center and right wheel center
    front_overhang: 0.32  # between front wheel center and vehicle front
    rear_overhang: 0.36   # between rear wheel center and vehicle rear
    left_overhang: 0.1    # between left wheel center and vehicle left
    right_overhang: 0.1   # between right wheel center and vehicle right
    vehicle_height: 1.4
    max_steer_angle: 0.25 # [rad]